const ActionTypes = {
    GET_MENUTYPES: 'GET_MENUTYPES',
    GET_USERINFO: 'GET_USERINFO',
    GET_SENSORTYPES: 'GET_SENSORTYPES',
    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    CHANGE_VALUENOTIFICATION: 'CHANGE_VALUENOTIFICATION',
    EDIT_NOTIFICATIONDATA: 'EDIT_NOTIFICATIONDATA',
    SAVE_CHANGESEDITUSER: 'SAVE_CHANGESEDITUSER',
    GET_PARAMETERSRANGE: 'GET_PARAMETERSRANGE'
  };

  export default ActionTypes;
